### ISSUE TITLE
Something about the various

### ISSUE THREAD

**Issue by zonegoalshall** [amanwalia92/KeyFramesExtraction#2]
Thanks for your help! I've tried your code using the command(I set the window size to 20) mentioned in your README, but frames saved by the script seems like the "every frame" not the key frames. Where could I find the extracted keyframes? Best wishes:)

**Comment by amanwalia123** [comment]
Can you share the plot generated?

**Comment by zonegoalshall** [comment]
![plot](https://user-images.githubusercontent.com/35282051/51009191-23b14100-158a-11e9-8c17-27292e7ce4f3.png)
Is this you want?

**Comment by amanwalia123** [comment]
Yeah it make sense why its giving you so many frames.Try using a bigger window size (probably x10) and see if it reduces frames. window length. One other solution i can think of is using `order` parameter in `argrelextrema` function used in line 171 of the script. Refer to the documentation here:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.argrelextrema.html. Using this you can control how many points to be used to compute local maxima.

**Comment by zonegoalshall** [comment]
Thanks bro! A bigger window size works!
