### ISSUE TITLE
key_frame numbers problem

### ISSUE THREAD

**Issue by chen-ming2019** [amanwalia92/KeyFramesExtraction#3]
Hi ,could the code set the numbers of extracting key_frame from video ?

**Comment by amanwalia123** [comment]
You can certainly do that although not in the original code. In line 171 where `frame_indexes` are obtained, use those to obtain the corresponding `sm_diff_array` values and store the corresponding values as (key, value) pair with key being `sm_diff_array` and value being `frame_indexes`. Once you get that, sort the (key, value) tuple according to keys(`sm_diff_array` values), then extract the top n frame indexes as per what you need. Rest of the code remains the same.

**Comment by chen-ming2019** [comment]
@amanwalia92 ok ,thanks!
