### ISSUE TITLE
how  to run   this program

### ISSUE THREAD

**Issue by yuanyuan1993** [amanwalia92/KeyFramesExtraction#4]
I run it by:   python scene_div.py 1.mp4 ./data/  10    
But the program reported an error:
  File "scene_div.py", line 63
    raise ValueError, "smooth only accepts 1 dimension arrays."
                    ^
SyntaxError: invalid syntax
Please tell me the correct command to run,thank you.

**Comment by amanwalia123** [comment]
can u put `print(diff_array.shape)` after line 169 and tell me the result

**Comment by yyyufei** [comment]
Did you solve it?
