### ISSUE TITLE
how to get the number of key frames?

### ISSUE THREAD

**Issue by cjhyy7190** [amanwalia92/KeyFramesExtraction#6]
Thanks for your good job!I have already successfully run this file.But I still have some questions.Different videos may have different numbers of the key frames.How to get the number of keyframes of different videos?And what is the function of the sliding window?Thank you.

**Comment by skyqwe123** [comment]
@cjhyy7190 If you find a strong solution in this way?

**Comment by skyqwe123** [comment]
@cjhyy7190  In my work, i have set the number of key frames according to the plot function, and it varies with the inputs

**Comment by Thinktan** [comment]
@skyqwe123  is there any paper related with this project?

**Comment by amanwalia92** [comment]
I don't have any paper written for this.
