### ISSUE TITLE
"smooth only accepts 1 dimension arrays."

### ISSUE THREAD

**Issue by yyyufei** [amanwalia92/KeyFramesExtraction#7]
Hi there, 

I was trying to use your code to do keyframe extraction, but I got "smooth only accepts 1 dimension arrays." Do you know is there anything I did wrong?

  File "scene_div.py", line 63
    raise ValueError, "smooth only accepts 1 dimension arrays."
                    ^
SyntaxError: invalid syntax

**Comment by yyyufei** [comment]
Figured out it caused by python version

**Comment by xiangtingkong** [comment]
> 弄清楚了是由python版本引起的
hi there
I want to know which version of python is required
